[window]
decorations = "None"
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[colors.primary]
background = '#000000'
foreground = '#f0f3f6'

[colors.normal]
black   = '#14191e'
red     = '#b43c29'
green   = '#00c200'
yellow  = '#c7c400'
blue    = '#2743c7'
magenta = '#bf3fbd'
cyan    = '#00c5c7'
white   = '#c7c7c7'

[colors.bright]
black   = '#676767'
red     = '#dc7974'
green   = '#57e690'
yellow  = '#ece100'
blue    = '#a6aaf1'
magenta = '#e07de0'
cyan    = '#5ffdff'
white   = '#feffff'

[font]
size = 12

[font.normal]
family = "NotoSansM Nerd Font"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
